name: "Build and Deploy to IIS via FTP"

#on: [push, workflow_dispatch]
on:
  push:
    branches:
      - main
  workflow_dispatch:  # ✅ 支援手動執行

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./testAuto.csproj

    - name: Build
      run: dotnet build ./testAuto.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish ./testAuto.csproj --no-build -c Release -o ./publish

    - name: Upload zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-auto-zip
        path: ./publish